spring:
  datasource:
    url: jdbc:mysql://192.168.0.111:3306/jpa
    username: root
    password: 688276
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  messages:
    basename: i18n/messages